puts "A module is block of reusable code that can be used, or \"mixed in,\""
puts "to many classes simply by using the \"include\" reserved word.\""

puts "Example: "
puts "module Odor"
puts "  def info(smell)"
puts "    puts \"He smells \#{smell}.\""
puts "  end"
puts "end"
puts ""
puts "class Person"
puts "  indclude Odor"
puts "end"
puts ""
puts "josh = Person.new"
puts "josh.info(\"bad\")"
puts "=> He smells bad."