puts "We create an object in Ruby by instantiating a new object from a class using the .new method."
puts "Example: "
puts "class Person"
puts "  def info(smell)"
puts "    puts \"He smells \#{smell}.\""
puts "  end"
puts "end"
puts "josh = Person.new"
puts "josh.info(\"bad\")"
puts "=> He smells bad."